### ISSUE TITLE
Move contributors bios into pages, and generate full list with shortcode

### ISSUE THREAD

**Issue by geealbers** [thegetty/mummyportraits#9]
The contributor bios currently in `contributors.md` should be moved to the page YAML of their individual papers. For instance, Jessica Arista's bio would go into `part-one/8.md` as:

```yaml
- first_name: Jessica
  last_name: Arista
  bio: "Jessica Arista was an assistant objects conservator at the Museum of Fine Arts, Boston, from 2013 to 2018. She graduated from the Winterthur/University of Delaware Program in Art Conservation in 2010 with an MS in objects conservation, and she is a professional associate member of the American Institute for Conservation (AIC)."
```
Note that the name as it appears in the bio, should also be made roman text rather than bold. And I believe that if the contributor is listed in more than one paper, their bio only needs to appear in the first one for it to display as described below, but this will need to be double checked.

Once all the bios have been moved to their respective papers, they can be deleted from `contributors.md`. To then generate the list on that page, a shortcode can be used, which will find all the contributors from across the publication and display their names, their bios, and a link to the paper(s) they contributed.

```
{{< q-contributor range="all" format="bio" >}}
```

The names should be double checked, as any variance in their spelling will create duplicate entries in the `q-contributor` shortcode output. For instance, it looks like there's a Marc Walton and a Mark Walton, and both Caroline Cartwright and Caroline R. Cartwright.
